version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: datadog
    versions:
    - 0.39.0
    - 0.40.0
    - 0.40.1
  - dependency-name: schedule
    versions:
    - 1.0.0
