version: '3.5'
secrets:
  DB_HOST:
    external: true
  DB_NAME:
    external: true
  DB_USER:
    external: true
  DB_PASS:
    external: true
  NB_USERNAME:
    external: true
  NB_PASSWORD:
    external: true
services:
  nb:
    image: nb:8da70de
    build: ./src
    secrets:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
      - NB_USERNAME
      - NB_PASSWORD
  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=$DD_API_KEY
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
