version: '3.5'
secrets:
  DB_HOST:
    external: true
  DB_NAME:
    external: true
  DB_USER:
    external: true
  DB_PASS:
    external: true
  NB_USERNAME:
    external: true
  NB_PASSWORD:
    external: true
services:
  nb:
    image: nb:latest
    deploy:
      replicas: 3
    build: ./src
    secrets:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
      - NB_USERNAME
      - NB_PASSWORD

networks:
  monitoring:
    external: true
