ALTER TABLE domains ADD COLUMN (created DATETIME DEFAULT CURRENT_TIMESTAMP, modified DATETIME DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP);
ALTER TABLE stories ADD COLUMN (created DATETIME DEFAULT CURRENT_TIMESTAMP, modified DATETIME DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP);
