ALTER TABLE domains ADD COLUMN (created DATETIME DEFAULT CURRENT_TIMESTAMP, modified DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP);
ALTER TABLE stories ADD COLUMN (created DATETIME DEFAULT CURRENT_TIMESTAMP, modified DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP);
