version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            cd src
            pip install -r requirements.txt
      - run:
          name: Test Python 3 compatibility
          command: |
            cd src
            python -m py_compile app.py
            find . -name "*.py" -exec python -m py_compile {} \;
